### ISSUE TITLE
CDFF -> DFKI-RIC

### ISSUE THREAD

**Issue by AlexanderFabisch** [Bengt/Awesome-DFKI#3]
Hi, I just found this collection. Awesome list. It would be nice if you could communicate this to the whole DFKI, since I didn't find any information about it anywhere.

However, I also have to correct something. CDFF (https://gitlab.com/h2020src/og3) is a software framework that was developed in the InFuse project by DFKI RIC in Bremen (and other partners of the consortium).

**Comment by fnogatz** [comment]
Hi @AlexanderFabisch, and greetings to Bremen :wave:

Yeah, I think the only official DFKI page that currently links to the @DFKI namespace is the intranet ABC entry on [*Dataset Publishing Guidelines*](https://intranet.dfki.de/services/know_how_pool/438/public_viewabc), thanks to @joernhees. Where would you expect to additionally find some hints about this namespace or this *Awesome DFKI* list?

Feel free to create a PR that corrects the CDFF entry! (Otherwise I'll do so in the next days.)

**Comment by AlexanderFabisch** [comment]
> Where would you expect to additionally find some hints about this namespace or this Awesome DFKI list?

Maybe send an email to all DFKI employees (at least once). Maybe we can link it at the main DFKI page. I believe software is as important as publications in computer science research and deserves a visible place there. :)

**Comment by fnogatz** [comment]
Good points. I'll e-mail the UK (again). At least we should highlight it in our quarterly internal newsletter.
